spring.application.name=workwave
spring.datasource.url=jdbc:postgresql://s00-vecarbonapp:32768/workwave
spring.datasource.username=postgres
spring.datasource.password=123qwe
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

## Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE