spring.datasource.url=jdbc:postgresql://s00-vecarbonapp:32769/workwave
spring.datasource.username=postgres
spring.datasource.password=123qwe

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

#liquibase config
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

#Mail SMTP config
workwave.service.mail.enabled=false
