spring.datasource.url=${DATABASE.URL}
spring.datasource.username=${DATABASE.USERNAME}
spring.datasource.password=${DATABASE.PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=true

#liquibase config
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

#Mail SMTP config
workwave.service.mail.enabled=${MAIL.SERVICE.ENABLED}
spring.mail.host=smtp.vinci-energies.net
spring.mail.port=25

#Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.url=/api-docs


spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/cae7d061-08f3-40dd-80c3-3c0b8889224a/v2.0
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/cae7d061-08f3-40dd-80c3-3c0b8889224a/discovery/v2.0/keys
app.jwt.issuer-uri=https://login.microsoftonline.com/cae7d061-08f3-40dd-80c3-3c0b8889224a/v2.0
app.jwt.connect-timeout-ms=${JWT_CONNECT_TIMEOUT_MS:15000}
app.jwt.read-timeout-ms=${JWT_READ_TIMEOUT_MS:15000}

app.storage.user-contracts-dir=${USER_CONTRACTS_DIR:uploads/user-contracts}

